"""Pipeline orchestration that invokes an internal repository agent function."""

import asyncio

from src.models.schemas import GenerateOptions, JobResult


class DocumentationOrchestrator:
    """Coordinate internal agent invocation and normalize output for storage/API."""

    def __init__(self, timeout_seconds: int) -> None:
        """Initialize orchestrator runtime settings.

        Args:
            timeout_seconds: End-to-end timeout applied to each generation run.
        """
        self._timeout_seconds = timeout_seconds

    async def run(self, github_url: str, options: GenerateOptions) -> JobResult:
        """Generate README content through the internal agent function.

        Args:
            github_url: Repository URL received from the API request.
            options: Generation options forwarded to ADK.

        Returns:
            A job result containing generated markdown.
        """

        async def _run_pipeline() -> JobResult:
            """Execute internal agent call and convert response to ``JobResult``."""
            agent_output = await self._invoke_agent(
                github_url=github_url,
                options=options,
            )
            readme = agent_output.get("readme.md")
            if not isinstance(readme, str) or not readme.strip():
                raise ValueError("Agent output missing 'readme.md'")
            return JobResult(markdown=readme)

        return await asyncio.wait_for(_run_pipeline(), timeout=self._timeout_seconds)

    async def _invoke_agent(self, github_url: str, options: GenerateOptions) -> dict:
        """Dummy in-repo agent invocation.

        This placeholder simulates the local agent contract and will be
        replaced by real agent logic later.
        """
        await asyncio.sleep(0)
        return {
            "readme.md": (
                "# Generated README\n\n"
                f"Repository: {github_url}\n\n"
                "This README was generated by the internal agent placeholder.\n"
                f"Options: {options.model_dump(mode='json')}\n"
            )
        }
